### ISSUE TITLE
Join strings

### ISSUE THREAD

**Issue by gustavwilliam** [gurkult/py-gurklang#14]
There would be two main use cases of a `join` jar:
- Join two strings
- Join linked lists of strings

```elixir
>>> "Gustav" :name var
>>> "Hello" name " " join println
"Hello Gustav"
```
```elixir
>>> ("Hello" ("Gustav" ())) " " join println
"Hello Gustav"
>>> {"Hello" "Gustav"}] " " join println
"Hello Gustav"
```

In general, this would be the syntax for the two cases:
```elixir
"first" "second" "joiner" join
{"first" "second" ... "final"}] "joiner" join
```

**Comment by decorator-factory** [comment]
I'd use `concat` or `++` to add strings. Those operations are pretty different.

**Comment by lavirlifiliol** [comment]
I would take inspiration from raku and use ~

**Comment by gustavwilliam** [comment]
@decorator-factory So you're saying that the following should exist? Why separate it?
```elixir
"first" "second" "joiner" concat
{"first" "second" ... "final"}] "joiner" join
```

Also, do you think that the joiner is a good idea? It could get quite annoying to have to type that out every time.

**Comment by decorator-factory** [comment]
`"Hello, " "world" concat -- "Hello, world"`

**Comment by gustavwilliam** [comment]
That would remove the joiner, yeah.

**Comment by lavirlifiliol** [comment]
I am not too fond of having a function do 2 different things, since someone screwing up and having the function do the wrong thing rather than just error would be annoying. And since you don't actually see what args are passed, it could be hard to tell which one is used.

**Comment by decorator-factory** [comment]
Yeah, I think we should make distinct functions for distinct operations.

**Comment by gustavwilliam** [comment]
This would be the function for concat: 
```elixir
"first" "second" concat  # "firstsecond"
```
And for join, do we want the joiner or not?
```elixir
{"first" "second" "third"}] "." join  # "first.second.third"
```
Considering that join wouldn't be used for simple two string concatenations, it seems reasonable to provide some more customisability.

**Comment by decorator-factory** [comment]
Yeah, `concat` would be `+` in Python, and `join` would be... well, `join` 

I think we can follow @lavirlifiliol 's advice and just do `python -c "print(dis(str))" | stdlib/strings.py`

**Comment by gustavwilliam** [comment]
We have join and concat now.
